#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HornsAndHooves.Droid.Resource", IsApplication=true)]

namespace HornsAndHooves.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drop = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int home_default = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int home_downed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_app = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int next_default = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int next_downed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pict1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int pict10 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int pict11 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int pict12 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pict13 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pict14 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int pict15 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int pict16 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int pict2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int pict3 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int pict4 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int pict5 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int pict6 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int pict7 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int pict8 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int pict9 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int previous_default = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int previous_downed = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int speaker_off = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int speaker_on = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int text_off = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int text_on = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int title_background = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f030000
			public const int a01 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int a02 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int a03 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int a04 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int a05 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int a06 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int a07 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int a08 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int a09 = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int a10 = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int a11 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int a12 = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int a13 = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int a14 = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int a15 = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int a16 = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int a17 = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int C10 = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int C11_1 = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int C11_2 = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int C12_1 = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int C12_2 = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int C13 = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int C14 = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int C15 = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int C3_1 = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int C3_2 = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int C7 = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int C8 = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int C9 = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int Cat = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int detskiy_smeh = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int dog = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int kryshka_kastuli = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int raskat_groma = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int teapot = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int upal = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int zvonok_velosipeda = 2130903077;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
	}
}
#pragma warning restore 1591
